kind: pipeline
type: kubernetes
name: deployment

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

# Learn more: https://plugins.drone.io/plugins/hugo
  - name: build
    image: plugins/hugo
    volumes:
      - name: build
        path: /hugo-build
    settings:
      validate: true
      output: /hugo-build

# Learn more: https://plugins.drone.io/plugins/ftps
  - name: deploy
    image: cschlosser/drone-ftps
    volumes:
      - name: build
        path: /drone/src/public
    environment:
      FTP_USERNAME:
        from_secret: FTP_USERNAME
      FTP_PASSWORD:
        from_secret: FTP_PASSWORD
      PLUGIN_HOSTNAME: www212.your-server.de:21
      PLUGIN_SECURE: true
      PLUGIN_SRC_DIR: /public
      PLUGIN_DEST_DIR: /

trigger:
  event:
    - tag

volumes:
  - name: build
    temp: {}
